version: "3.7"

services:
  db:
    image: postgres:latest
    container_name: db
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8081:8080"

volumes:
  db:
    driver: local
  cache:
    driver: local
